import 'package:flutter/material.dart';
import 'package:responsive_design/profile_card.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This is the file generated by the CLI

void main() async {

  // intialize the firebase service before we display widgets
  // make sure flutter is ready before we call login service
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // this widget is the root of your application
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Responsive Design',
      home: const ProfileCard()
    );
  }
}




// firebase testing

// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // This is the file generated by the CLI

// void main() async {
//   // 1. Ensure Flutter bindings are initialized
//   WidgetsFlutterBinding.ensureInitialized();

//   // 2. Initialize Firebase
//   // We use the 'options' from the file the CLI generated
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );

//   runApp(const MyApp());
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return const MaterialApp(
//       home: Scaffold(
//         body: Center(
//           child: Text(
//             'Firebase Initialized Successfully!',
//             style: TextStyle(fontSize: 24),
//           ),
//         ),
//       ),
//     );
//   }
// }
