// import 'package:flutter/material.dart';
// import 'package:responsive_design/profile_card.dart';

// void main() {
//   runApp(const MyApp());
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   // this widget is the root of your application
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Responsive Design',
//       home: const ProfileCard()
//     );
//   }
// }

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This is the file generated by the CLI

void main() async {
  // 1. Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase
  // We use the 'options' from the file the CLI generated
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text(
            'Firebase Initialized Successfully!',
            style: TextStyle(fontSize: 24),
          ),
        ),
      ),
    );
  }
}
